---
title: Illustration of the methodology
author: Markus Riedl
date: "`r Sys.Date()`"
toc: true
number-sections: true
format:
  html:
    embed-resources: true
knitr:
  opts_chunk:
    collapse: true
---


```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(targets)
  library(tidyplots)
  library(ggpubr)
  library(here)
})
```

```{r}
color_theme <- c("grey", colors_discrete_friendly[c(1, 3, 5)])
base_fontsize <- 18
```

Create sample data for the boxplot.

```{r}
sample_data <- bind_rows(
  tibble(gene = "Gene A", dataset = "1", expr = rnorm(50, sd = 20)),
  tibble(gene = "Gene A", dataset = "2", expr = rnorm(50, sd = 20)),
  tibble(gene = "Gene B", dataset = "1", expr = rnorm(50, sd = 4)),
  tibble(gene = "Gene B", dataset = "2", expr = rnorm(50, sd = 4)),
  tibble(gene = "Gene C", dataset = "1", expr = rnorm(50, sd = 15)),
  tibble(gene = "Gene C", dataset = "2", expr = rnorm(50, sd = 6))
)
```


```{r}
methods_boxplot <- sample_data %>%
  tidyplot(x = dataset, y = expr, color = gene) %>%
  add_boxplot() %>%
  add_data_points_beeswarm() %>%
  facet("gene") %>%
  remove_legend() %>%
  remove_y_axis_labels() %>%
  remove_y_axis_ticks() %>%
  adjust_y_axis_title("Gene Expression") %>%
  adjust_x_axis_title("Dataset") %>%
  adjust_size(90, 90) %>%
  adjust_font(fontsize = base_fontsize) %>%
  adjust_theme_details(
    strip.text = element_text(size = 18)
  ) %>%
  adjust_colors(color_theme[-1])

methods_boxplot
```

Create sample data for the scatter plot.
```{r}
X <- matrix(c(0.8, 0.3, 0.3, 0.8), 2, 2)
cov <- crossprod(X)
scatter_sample <- MASS::mvrnorm(300, c(0, 0), cov) %>%
  as.data.frame() %>%
  mutate(type = factor("sampled", levels = c("sampled", "A", "B", "C"))) %>%
  bind_rows(
    examples <- data.frame(
      type = factor(c("A", "B", "C")),
      V1 = c(2.1, -2.1, 1.5),
      V2 = c(2.1, -2.1, -1)
    )
  )
```

```{r}
methods_scatter <- scatter_sample %>%
  tidyplot(x = V1, y = V2, color = type) %>%
  adjust_colors(color_theme) %>%
  adjust_x_axis(limits = c(-3, 3)) %>%
  adjust_y_axis(limits = c(-3, 3)) %>%
  adjust_x_axis_title("Variance Dataset 1") %>%
  adjust_y_axis_title("Variance Dataset 2") %>%
  remove_x_axis_labels() %>%
  remove_x_axis_ticks() %>%
  remove_y_axis_labels() %>%
  remove_y_axis_ticks() %>%
  remove_legend() %>%
  adjust_font(fontsize = base_fontsize) %>%
  adjust_size(90, 90) %>%
  add(theme(plot.margin = margin(l = 40))) %>%
  add_data_points(data = filter_rows(type == "A")) %>%
  add_data_labels(
    data = filter_rows(type == "A"), label = type,
    fontsize = 20
  ) %>%
  add_data_points(data = filter_rows(type == "B")) %>%
  add_data_labels(
    data = filter_rows(type == "B"), label = type,
    fontsize = 20
  ) %>%
  add_data_points(data = filter_rows(type == "C")) %>%
  add_data_labels(
    data = filter_rows(type == "C"), label = type,
    fontsize = 20
  ) %>%
  add_data_points(data = filter_rows(type == "sampled"))

methods_scatter
```

```{r}
pca_sample <- prcomp(scatter_sample[1:2])

scatter_sample_pca <- scatter_sample %>%
  mutate(
    PC1 = pca_sample$x[, 1],
    PC2 = pca_sample$x[, 2]
  )

quant_pc1 <- quantile(scatter_sample_pca$PC1, c(0.08, 0.92))

methods_pca <- scatter_sample_pca %>%
  tidyplot(x = PC1, y = PC2, color = type) %>%
  adjust_font(fontsize = 20) %>%
  adjust_x_axis(limits = c(-3.9, 3.9)) %>%
  adjust_y_axis(limits = c(-3.9, 3.9)) %>%
  remove_x_axis_labels() %>%
  remove_x_axis_ticks() %>%
  remove_y_axis_labels() %>%
  remove_y_axis_ticks() %>%
  remove_legend() %>%
  adjust_font(fontsize = base_fontsize) %>%
  adjust_size(90, 90) %>%
  adjust_colors(color_theme) %>%
  add(theme(plot.margin = margin(l = 40))) %>%
  add_reference_lines(x = 0, y = 0, color = "grey40") %>%
  add_data_points(
    data = filter_rows(type == "sampled")
  ) %>%
  add_data_points(
    data = filter_rows(type != "sampled")
  ) %>%
  add_data_labels(
    data = filter_rows(type != "sampled"), label = type,
    fontsize = 20
  )

methods_pca
```

## Figure

```{r}
# (methods_figure <- methods_boxplot - methods_scatter + methods_pca)
# tidyplots::save_plot(methods_figure, "tmp/test.pdf")
```
